In [1]:
A = [[1, 4, 5], 
    [-5, 8, 9]]

In [2]:
print(A)

[[1, 4, 5], [-5, 8, 9]]


In [3]:
# empty list
my_list = []

# list of integers
my_list = [1, 2, 3]

# list with mixed datatypes
my_list = [1, "Hello", 3.4]

In [5]:
type(my_list)


list

In [6]:
# nested list
my_list = ["mouse", [8, 4, 6], ['a']]

In [7]:
my_list

['mouse', [8, 4, 6], ['a']]

In [8]:
#List Index
my_list = ['p','r','o','b','e']

In [9]:
print(my_list[0])

p


In [14]:
print(my_list[1])

r


In [15]:
# Nested List
n_list = ["Happy", [2,0,1,5]]

In [24]:
print(n_list[0][0])

H


In [25]:
print(n_list[1][0])

2


In [26]:
#Negative indexing
#Python allows negative indexing for its sequences.
#The index of -1 refers to the last item, -2 to the second last item and so on.

In [27]:
my_list = ['p','r','o','b','e']
print(my_list[-1])

e


In [34]:
print(my_list[-5])

p


In [35]:
#How to slice lists in Python?

In [36]:
my_list = ['p','r','o','g','r','a','m','i','z']

In [37]:
print(my_list[2:5])

['o', 'g', 'r']


In [41]:
print(my_list[0:9])

['p', 'r', 'o', 'g', 'r', 'a', 'm', 'i', 'z']


In [44]:
print(my_list[:-5])

['p', 'r', 'o', 'g']


In [45]:
print(my_list[5:])

['a', 'm', 'i', 'z']


In [46]:
print(my_list[:])

['p', 'r', 'o', 'g', 'r', 'a', 'm', 'i', 'z']


In [47]:
#How to change or add elements to a list?

In [48]:
odd = [2, 4, 6, 8]

In [53]:
odd[0] = 1

In [54]:
print(odd)

[1, 4, 6, 1]


In [55]:
#We can add one item to a list using append() method or add several items using extend() method

In [56]:
odd = [1, 3, 5]

In [57]:
odd.append(7)

In [58]:
print(odd)

[1, 3, 5, 7]


In [59]:
odd.extend([9, 11, 13])

In [60]:
print(odd)

[1, 3, 5, 7, 9, 11, 13]


In [61]:
odd = [1, 3, 5]

In [62]:
print(odd + [9, 7, 5])

[1, 3, 5, 9, 7, 5]


In [63]:
odd+[6,7,8]

[1, 3, 5, 6, 7, 8]

In [65]:
"re"*3

'rerere'

In [66]:
["re"]*3

['re', 're', 're']

In [67]:
#we can insert one item at a desired location by using the method insert() 
#or insert multiple items by squeezing it into an empty slice of a list

In [68]:
odd = [1, 9]

In [69]:
odd.insert(1,3)

In [70]:
odd

[1, 3, 9]

In [81]:
odd[2:5]=[5,7]

In [82]:
print(odd)

[1, 3, 5, 7]


In [83]:
#delete or remove elements from a lis

In [84]:
my_list = ['p','r','o','b','l','e','m']

In [85]:
del my_list[2]

In [86]:
my_list

['p', 'r', 'b', 'l', 'e', 'm']

In [87]:
del my_list[1:5]

In [88]:
my_list

['p', 'm']

In [89]:
del my_list

In [90]:
my_list

NameError: name 'my_list' is not defined

In [110]:
my_list = ['p','r','o','b','l','e','m']

In [111]:
my_list.remove('p')

In [112]:
my_list

['r', 'o', 'b', 'l', 'e', 'm']

In [113]:
print(my_list.pop(1))

o


In [114]:
print(my_list)

['r', 'b', 'l', 'e', 'm']


In [115]:
print(my_list.pop())

m


In [116]:
print(my_list)

['r', 'b', 'l', 'e']


In [117]:
my_list.clear()

In [118]:
print(my_list)

[]


In [119]:
my_list = ['p','r','o','b','l','e','m']

In [120]:
my_list[2:3] = []

In [121]:
my_list

['p', 'r', 'b', 'l', 'e', 'm']

In [122]:
my_list[2:5] = []

In [123]:
my_list

['p', 'r', 'm']

In [124]:
#examples
my_list = [3, 8, 1, 6, 0, 8, 4]

In [125]:
print(my_list.index(8))

1


In [126]:
print(my_list.count(8))

2


In [127]:
my_list.sort()

In [128]:
print(my_list)

[0, 1, 3, 4, 6, 8, 8]


In [129]:
my_list.reverse()

In [130]:
print(my_list)

[8, 8, 6, 4, 3, 1, 0]


In [131]:
pow2 = [2 ** x for x in range(10)]

In [132]:
pow2

[1, 2, 4, 8, 16, 32, 64, 128, 256, 512]

In [133]:
my_list = ['p','r','o','b','l','e','m']

In [134]:
print('p' in my_list)

True


In [135]:
print('a' in my_list)

False


In [136]:
for fruit in ['apple','banana','mango']:
    print("I like",fruit)

I like apple
I like banana
I like mango


In [137]:
#matrix
A = [[1, 4, 5, 12], 
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]]

In [139]:
print("A =", A)

A = [[1, 4, 5, 12], [-5, 8, 9, 0], [-6, 7, 11, 19]]


In [143]:
print("A[1] =", A[1])      # 2nd row

A[1] = [-5, 8, 9, 0]


In [147]:
print("A[1][2] =", A[1][2])   # 3rd element of 2nd row

A[1][2] = 9


In [153]:
print("A[0][-1] =", A[0][-1])   # Last element of 1st Row

A[0][-1] = 12


In [158]:
column = [];  # empty list
for row in A:
    column.append(row[2])
print("3rd column =", column)

3rd column = [5, 9, 11]


In [159]:
#Add two matrix

In [163]:
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

In [164]:
Y = [[5,8,1],
    [6,7,3],
    [4,5,9]]
result = [[0,0,0],
         [0,0,0],
         [0,0,0]]

In [165]:
# iterate through rows
for i in range(len(X)):
   # iterate through columns
   for j in range(len(X[0])):
       result[i][j] = X[i][j] + Y[i][j]

for r in result:
   print(r)

[17, 15, 4]
[10, 12, 9]
[11, 13, 18]


In [166]:
#Transpose of Matrix
X = [[12,7],
    [4 ,5],
    [3 ,8]]

result = [[0,0,0],
         [0,0,0]]

# iterate through rows
for i in range(len(X)):
   # iterate through columns
   for j in range(len(X[0])):
       result[j][i] = X[i][j]

for r in result:
   print(r)

[12, 4, 3]
[7, 5, 8]


In [167]:
#Matrix Multiplication
# 3x3 matrix
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]
# 3x4 matrix
Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]
# result is 3x4
result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]

# iterate through rows of X
for i in range(len(X)):
   # iterate through columns of Y
   for j in range(len(Y[0])):
       # iterate through rows of Y
       for k in range(len(Y)):
           result[i][j] += X[i][k] * Y[k][j]

for r in result:
   print(r)

[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


In [168]:
#NumPy Array
#NumPy is a package for scientific computing which has support for a powerful N-dimensional array object

In [169]:
import numpy as np

In [170]:
a = np.array([1, 2, 3])

In [171]:
print(a)

[1 2 3]


In [172]:
print(type(a))

<class 'numpy.ndarray'>


In [173]:
A = np.array([[1, 2, 3], [3, 4, 5]])
print(A)

[[1 2 3]
 [3 4 5]]


In [174]:
A = np.array([[1.1, 2, 3], [3, 4, 5]]) # Array of floats
print(A)

[[1.1 2.  3. ]
 [3.  4.  5. ]]


In [175]:
A = np.array([[1, 2, 3], [3, 4, 5]], dtype = complex) # Array of complex numbers
print(A)

[[1.+0.j 2.+0.j 3.+0.j]
 [3.+0.j 4.+0.j 5.+0.j]]


In [176]:
zeors_array = np.zeros( (2, 3) )   #array of zeros
print(zeors_array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [178]:
ones_array = np.ones( (1, 5), dtype=np.int32 ) #specifying dtype
print(ones_array)

[[1 1 1 1 1]]


In [179]:
A = np.arange(4)
print('A =', A)

A = [0 1 2 3]


In [180]:
B = np.arange(12).reshape(2, 6)
print('B =', B)

B = [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [181]:
#Addition of Two Matrices
A = np.array([[2, 4], [5, -6]])
B = np.array([[9, -3], [3, 6]])
C = A + B      # element wise addition
print(C)

[[11  1]
 [ 8  0]]


In [182]:
#Multiplication of Two Matrices
A = np.array([[3, 6, 7], [5, -3, 0]])
B = np.array([[1, 1], [2, 1], [3, -3]])
C = a.dot(B)
print(C)

[14 -6]


In [183]:
np.dot(3,4)

12

In [184]:
#Transpose
A = np.array([[1, 1], [2, 1], [3, -3]])
print(A.transpose())

[[ 1  2  3]
 [ 1  1 -3]]


In [185]:
#Access matrix elements
A = np.array([2, 4, 6, 8, 10])

print("A[0] =", A[0])     # First element     
print("A[2] =", A[2])     # Third element 
print("A[-1] =", A[-1])   # Last element

A[0] = 2
A[2] = 6
A[-1] = 10


In [186]:
A = np.array([[1, 4, 5, 12],
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]])

#  First element of first row
print("A[0][0] =", A[0][0])  

# Third element of second row
print("A[1][2] =", A[1][2])

# Last element of last row
print("A[-1][-1] =", A[-1][-1])

A[0][0] = 1
A[1][2] = 9
A[-1][-1] = 19


In [187]:
#Access rows of a Matrix
A = np.array([[1, 4, 5, 12], 
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]])

print("A[0] =", A[0]) # First Row
print("A[2] =", A[2]) # Third Row
print("A[-1] =", A[-1]) # Last Row (3rd row in this case)

A[0] = [ 1  4  5 12]
A[2] = [-6  7 11 19]
A[-1] = [-6  7 11 19]


In [188]:
#Access columns of a Matrix
A = np.array([[1, 4, 5, 12], 
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]])

print("A[:,0] =",A[:,0]) # First Column
print("A[:,3] =", A[:,3]) # Fourth Column
print("A[:,-1] =", A[:,-1]) # Last Column (4th column in this case)

A[:,0] = [ 1 -5 -6]
A[:,3] = [12  0 19]
A[:,-1] = [12  0 19]


In [189]:
#Slicing of a Matrix
letters = np.array([1, 3, 5, 7, 9, 7, 5])

In [190]:
# 3rd to 5th elements
print(letters[2:5])
# 1st to 4th elements
print(letters[:-5])
# 6th to last elements
print(letters[5:])
# 1st to last elements
print(letters[:])
# reversing a list
print(letters[::-1])

[5 7 9]
[1 3]
[7 5]
[1 3 5 7 9 7 5]
[5 7 9 7 5 3 1]


In [192]:
A = np.array([[1, 4, 5, 12, 14], 
    [-5, 8, 9, 0, 17],
    [-6, 7, 11, 19, 21]])

In [195]:
print(A[:2, :4])  # two rows, four columns

[[ 1  4  5 12]
 [-5  8  9  0]]


In [196]:
print(A[:1,])  # first row, all columns

[[ 1  4  5 12 14]]


In [197]:
print(A[:,2])  # all rows, second column

[ 5  9 11]


In [198]:
print(A[:, 2:5])  # all rows, third to fifth column

[[ 5 12 14]
 [ 9  0 17]
 [11 19 21]]
